import Link from 'next/link';
import Reveal from '@/components/Reveal';
import { aboutImage, aboutAlt, aboutSecondaryImage, aboutSecondaryAlt } from '@/data/site';

export default function AboutSection() { return <section className="noise-overlay bg-navy-950 py-24 md:py-32"><div className="section-padding"><div className="container-wide grid gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:gap-24">
  <Reveal className="relative"><div className="overflow-hidden rounded-[2rem] border border-white/10"><img src={aboutImage} alt={aboutAlt} className="aspect-[4/4.6] w-full object-cover transition duration-700 hover:scale-[1.02]"/></div><div className="absolute -bottom-7 -right-5 hidden w-44 overflow-hidden rounded-2xl border-8 border-navy-950 shadow-2xl md:block"><img src={aboutSecondaryImage} alt={aboutSecondaryAlt} className="aspect-square w-full object-cover"/></div><div className="absolute left-5 top-5 rounded-full border border-white/10 bg-navy-950/75 px-3 py-2 text-[9px] font-bold uppercase tracking-[.22em] text-bone-200 backdrop-blur">About Kalycor</div></Reveal>
  <div><Reveal><div className="mb-5 flex items-center gap-3"><span className="h-px w-8 bg-accent"/><span className="eyebrow-accent">The Kalycor approach</span></div></Reveal><Reveal delay={80}><h2 className="max-w-3xl text-[clamp(2.7rem,5vw,5rem)] font-extrabold leading-[.95] tracking-[-.05em] text-white">Protection built around <span className="text-accent">your operation.</span></h2></Reveal><Reveal delay={160}><p className="mt-7 max-w-2xl text-base leading-7 text-steel-400 md:text-lg md:leading-8">Every site has its own rhythm, risks and people. Kalycor brings security personnel, surveillance technology and facility support together into one coordinated operating model.</p></Reveal><Reveal delay={240}><p className="mt-4 max-w-2xl text-sm leading-6 text-steel-500">We start with the environment, then build the coverage — so security feels integrated into your business instead of being bolted on.</p></Reveal>
  <Reveal delay={320}><div className="mt-9 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="mb-2 text-[10px] font-bold uppercase tracking-[.2em] text-accent">Site-specific</div><p className="text-sm leading-6 text-bone-200">Protocols, staffing and coverage shaped around your location.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="mb-2 text-[10px] font-bold uppercase tracking-[.2em] text-accent">Coordinated</div><p className="text-sm leading-6 text-bone-200">Security and facility services working as one team.</p></div></div></Reveal>
  <Reveal delay={400}><Link href="/about" className="mt-8 inline-flex items-center gap-3 text-xs font-extrabold uppercase tracking-[.18em] text-white link-underline">Learn more about Kalycor <span className="text-accent">→</span></Link></Reveal></div>
</div></div></section>; }
